import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import { Icon } from "./_components/icon";
import Script from "next/script";

export const metadata: Metadata = {
  title: "TDSSKETCH",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: Icon }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`tb-dark-theme v2`}>
      <head>
        <Script
          strategy="beforeInteractive"
          src="https://cdn.jsdelivr.net/npm/vue@2.6.14"
        />

        <script data-savepage-type="text/javascript" type="text/plain" async="" charset="utf-8" data-savepage-src="https://www.gstatic.com/recaptcha/releases/rKbTvxTxwcw5VqzrtN-ICwWt/recaptcha__ru.js" crossorigin="anonymous" integrity="sha384-cbvmDpdnj4jSaF/uBlsQrk3jhmuXSCu6j6w8/p2Bv8YjRkVLHtbJvTLlkqn1bMFP">
        </script>
        <script data-savepage-type="text/javascript" type="text/plain" async="" data-savepage-src="https://widget.intercom.io/widget/xilmcuk"></script>
      </head>
      <body className="mobile-search-mode">
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}